### ISSUE TITLE
Performance and Integration Questions for regvelo with Custom Data

### ISSUE THREAD

**Issue by JiehoonKwak** [theislab/regvelo#17]
Performance and Integration Questions for regvelo with Custom Data

Hi!
Thank you for creating such an amazing package! I’ve been exploring it with my own dataset, but I’m encountering significant delays during model training.

I tested it using an A100 GPU, as well as H200-SMX and L40 GPUs, but the estimated training time is extremely long—around 67:39:40 (with 162.50s/it on the L40).

I came across [issue #15](https://github.com/theislab/regvelo/issues/new?q=is%3Aissue&template=Blank+issue#15) and downgraded scvi-tools to version 1.2.0, but the problem persists.

- I followed the preliminary tutorial, modifying only the necessary parts for my dataset.
- My dataset (12 samples, scANVI-integrated) dimensions are as follows:
```
adata: (49499, 578)  
W: (578, 578)  
TF_list: 51  
```

I have a few additional questions:
1.	Should I process my data sample-by-sample instead of integrating multiple samples? Is `regvelo` robust to batch effects?
2.	If I need to process sample-by-sample, do you have any recommendations for integrating the outputs effectively?

It’s possible that I’ve made an error somewhere—please let me know if there’s anything I should verify or adjust.
Thank you again for this creative and inspiring work!

Best,
Jiehoon

**Comment by WWXkenmo** [comment]
Hi Jiehoon,

Thank you for your interest in our work!

Since Regvelo relies on a parallel numerical solver, the training time can be quite long, especially with datasets containing more than 40k cells. Additionally, I discourage performing dynamic inference on multiple disconnected samples with batch effects, as it may lead to incorrect kinetic inferences and spurious regulation predictions. I recommend focusing on interpreting dynamic results on each sample individually.

Regarding integration, it depends on the type of output you want to integrate. For certain downstream tasks, such as quantitative statistics inferred by Regvelo (e.g., perturbation effects), you can simply calculate the average values and use them for the final prediction.

Please let me know if you have any further questions!

Best regards,
Ken

**Comment by WWXkenmo** [comment]
Hi Jiehoon,

May I know further status? Please let me know if I can help anything!

Thanks,
Ken

**Comment by JiehoonKwak** [comment]
@WWXkenmo 

Dear Ken,

Thank you for following up and for your valuable advice. Running regvelo on individual samples has significantly improved performance and works seamlessly with my data. I truly appreciate your guidance on this matter.

I’ll continue to monitor for any updates to regvelo and explore its capabilities further. Wishing you a wonderful holiday season!

Best regards,
Jiehoon
